/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as ProducaoRouteImport } from './routes/producao'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as PagamentosRouteImport } from './routes/pagamentos'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutosIndexRouteImport } from './routes/produtos.index'
import { Route as EstoqueIndexRouteImport } from './routes/estoque.index'
import { Route as ProdutosImportacaoRouteImport } from './routes/produtos.importacao'
import { Route as PedidosNovoRouteImport } from './routes/pedidos.novo'
import { Route as EstoqueRetalhosRouteImport } from './routes/estoque.retalhos'
import { Route as EstoqueOrdensRouteImport } from './routes/estoque.ordens'
import { Route as EstoqueMovimentacoesRouteImport } from './routes/estoque.movimentacoes'

const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducaoRoute = ProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentosRoute = PagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosIndexRoute = ProdutosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProdutosRoute,
} as any)
const EstoqueIndexRoute = EstoqueIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EstoqueRoute,
} as any)
const ProdutosImportacaoRoute = ProdutosImportacaoRouteImport.update({
  id: '/importacao',
  path: '/importacao',
  getParentRoute: () => ProdutosRoute,
} as any)
const PedidosNovoRoute = PedidosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => PedidosRoute,
} as any)
const EstoqueRetalhosRoute = EstoqueRetalhosRouteImport.update({
  id: '/retalhos',
  path: '/retalhos',
  getParentRoute: () => EstoqueRoute,
} as any)
const EstoqueOrdensRoute = EstoqueOrdensRouteImport.update({
  id: '/ordens',
  path: '/ordens',
  getParentRoute: () => EstoqueRoute,
} as any)
const EstoqueMovimentacoesRoute = EstoqueMovimentacoesRouteImport.update({
  id: '/movimentacoes',
  path: '/movimentacoes',
  getParentRoute: () => EstoqueRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/estoque': typeof EstoqueRouteWithChildren
  '/historico': typeof HistoricoRoute
  '/pagamentos': typeof PagamentosRoute
  '/pedidos': typeof PedidosRouteWithChildren
  '/producao': typeof ProducaoRoute
  '/produtos': typeof ProdutosRouteWithChildren
  '/estoque/movimentacoes': typeof EstoqueMovimentacoesRoute
  '/estoque/ordens': typeof EstoqueOrdensRoute
  '/estoque/retalhos': typeof EstoqueRetalhosRoute
  '/pedidos/novo': typeof PedidosNovoRoute
  '/produtos/importacao': typeof ProdutosImportacaoRoute
  '/estoque/': typeof EstoqueIndexRoute
  '/produtos/': typeof ProdutosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/historico': typeof HistoricoRoute
  '/pagamentos': typeof PagamentosRoute
  '/pedidos': typeof PedidosRouteWithChildren
  '/producao': typeof ProducaoRoute
  '/estoque/movimentacoes': typeof EstoqueMovimentacoesRoute
  '/estoque/ordens': typeof EstoqueOrdensRoute
  '/estoque/retalhos': typeof EstoqueRetalhosRoute
  '/pedidos/novo': typeof PedidosNovoRoute
  '/produtos/importacao': typeof ProdutosImportacaoRoute
  '/estoque': typeof EstoqueIndexRoute
  '/produtos': typeof ProdutosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/estoque': typeof EstoqueRouteWithChildren
  '/historico': typeof HistoricoRoute
  '/pagamentos': typeof PagamentosRoute
  '/pedidos': typeof PedidosRouteWithChildren
  '/producao': typeof ProducaoRoute
  '/produtos': typeof ProdutosRouteWithChildren
  '/estoque/movimentacoes': typeof EstoqueMovimentacoesRoute
  '/estoque/ordens': typeof EstoqueOrdensRoute
  '/estoque/retalhos': typeof EstoqueRetalhosRoute
  '/pedidos/novo': typeof PedidosNovoRoute
  '/produtos/importacao': typeof ProdutosImportacaoRoute
  '/estoque/': typeof EstoqueIndexRoute
  '/produtos/': typeof ProdutosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/estoque'
    | '/historico'
    | '/pagamentos'
    | '/pedidos'
    | '/producao'
    | '/produtos'
    | '/estoque/movimentacoes'
    | '/estoque/ordens'
    | '/estoque/retalhos'
    | '/pedidos/novo'
    | '/produtos/importacao'
    | '/estoque/'
    | '/produtos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/historico'
    | '/pagamentos'
    | '/pedidos'
    | '/producao'
    | '/estoque/movimentacoes'
    | '/estoque/ordens'
    | '/estoque/retalhos'
    | '/pedidos/novo'
    | '/produtos/importacao'
    | '/estoque'
    | '/produtos'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/estoque'
    | '/historico'
    | '/pagamentos'
    | '/pedidos'
    | '/producao'
    | '/produtos'
    | '/estoque/movimentacoes'
    | '/estoque/ordens'
    | '/estoque/retalhos'
    | '/pedidos/novo'
    | '/produtos/importacao'
    | '/estoque/'
    | '/produtos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DashboardRoute: typeof DashboardRoute
  EstoqueRoute: typeof EstoqueRouteWithChildren
  HistoricoRoute: typeof HistoricoRoute
  PagamentosRoute: typeof PagamentosRoute
  PedidosRoute: typeof PedidosRouteWithChildren
  ProducaoRoute: typeof ProducaoRoute
  ProdutosRoute: typeof ProdutosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producao': {
      id: '/producao'
      path: '/producao'
      fullPath: '/producao'
      preLoaderRoute: typeof ProducaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamentos': {
      id: '/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof PagamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/': {
      id: '/produtos/'
      path: '/'
      fullPath: '/produtos/'
      preLoaderRoute: typeof ProdutosIndexRouteImport
      parentRoute: typeof ProdutosRoute
    }
    '/estoque/': {
      id: '/estoque/'
      path: '/'
      fullPath: '/estoque/'
      preLoaderRoute: typeof EstoqueIndexRouteImport
      parentRoute: typeof EstoqueRoute
    }
    '/produtos/importacao': {
      id: '/produtos/importacao'
      path: '/importacao'
      fullPath: '/produtos/importacao'
      preLoaderRoute: typeof ProdutosImportacaoRouteImport
      parentRoute: typeof ProdutosRoute
    }
    '/pedidos/novo': {
      id: '/pedidos/novo'
      path: '/novo'
      fullPath: '/pedidos/novo'
      preLoaderRoute: typeof PedidosNovoRouteImport
      parentRoute: typeof PedidosRoute
    }
    '/estoque/retalhos': {
      id: '/estoque/retalhos'
      path: '/retalhos'
      fullPath: '/estoque/retalhos'
      preLoaderRoute: typeof EstoqueRetalhosRouteImport
      parentRoute: typeof EstoqueRoute
    }
    '/estoque/ordens': {
      id: '/estoque/ordens'
      path: '/ordens'
      fullPath: '/estoque/ordens'
      preLoaderRoute: typeof EstoqueOrdensRouteImport
      parentRoute: typeof EstoqueRoute
    }
    '/estoque/movimentacoes': {
      id: '/estoque/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/estoque/movimentacoes'
      preLoaderRoute: typeof EstoqueMovimentacoesRouteImport
      parentRoute: typeof EstoqueRoute
    }
  }
}

interface EstoqueRouteChildren {
  EstoqueMovimentacoesRoute: typeof EstoqueMovimentacoesRoute
  EstoqueOrdensRoute: typeof EstoqueOrdensRoute
  EstoqueRetalhosRoute: typeof EstoqueRetalhosRoute
  EstoqueIndexRoute: typeof EstoqueIndexRoute
}

const EstoqueRouteChildren: EstoqueRouteChildren = {
  EstoqueMovimentacoesRoute: EstoqueMovimentacoesRoute,
  EstoqueOrdensRoute: EstoqueOrdensRoute,
  EstoqueRetalhosRoute: EstoqueRetalhosRoute,
  EstoqueIndexRoute: EstoqueIndexRoute,
}

const EstoqueRouteWithChildren =
  EstoqueRoute._addFileChildren(EstoqueRouteChildren)

interface PedidosRouteChildren {
  PedidosNovoRoute: typeof PedidosNovoRoute
}

const PedidosRouteChildren: PedidosRouteChildren = {
  PedidosNovoRoute: PedidosNovoRoute,
}

const PedidosRouteWithChildren =
  PedidosRoute._addFileChildren(PedidosRouteChildren)

interface ProdutosRouteChildren {
  ProdutosImportacaoRoute: typeof ProdutosImportacaoRoute
  ProdutosIndexRoute: typeof ProdutosIndexRoute
}

const ProdutosRouteChildren: ProdutosRouteChildren = {
  ProdutosImportacaoRoute: ProdutosImportacaoRoute,
  ProdutosIndexRoute: ProdutosIndexRoute,
}

const ProdutosRouteWithChildren = ProdutosRoute._addFileChildren(
  ProdutosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DashboardRoute: DashboardRoute,
  EstoqueRoute: EstoqueRouteWithChildren,
  HistoricoRoute: HistoricoRoute,
  PagamentosRoute: PagamentosRoute,
  PedidosRoute: PedidosRouteWithChildren,
  ProducaoRoute: ProducaoRoute,
  ProdutosRoute: ProdutosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
