/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as ProducaoRouteImport } from './routes/producao'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as PagamentosRouteImport } from './routes/pagamentos'
import { Route as OrcamentosRouteImport } from './routes/orcamentos'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutosIndexRouteImport } from './routes/produtos.index'
import { Route as ProdutosImportacaoRouteImport } from './routes/produtos.importacao'

const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducaoRoute = ProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentosRoute = PagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosRoute = OrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosIndexRoute = ProdutosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProdutosRoute,
} as any)
const ProdutosImportacaoRoute = ProdutosImportacaoRouteImport.update({
  id: '/importacao',
  path: '/importacao',
  getParentRoute: () => ProdutosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/historico': typeof HistoricoRoute
  '/orcamentos': typeof OrcamentosRoute
  '/pagamentos': typeof PagamentosRoute
  '/pedidos': typeof PedidosRoute
  '/producao': typeof ProducaoRoute
  '/produtos': typeof ProdutosRouteWithChildren
  '/produtos/importacao': typeof ProdutosImportacaoRoute
  '/produtos/': typeof ProdutosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/historico': typeof HistoricoRoute
  '/orcamentos': typeof OrcamentosRoute
  '/pagamentos': typeof PagamentosRoute
  '/pedidos': typeof PedidosRoute
  '/producao': typeof ProducaoRoute
  '/produtos/importacao': typeof ProdutosImportacaoRoute
  '/produtos': typeof ProdutosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/historico': typeof HistoricoRoute
  '/orcamentos': typeof OrcamentosRoute
  '/pagamentos': typeof PagamentosRoute
  '/pedidos': typeof PedidosRoute
  '/producao': typeof ProducaoRoute
  '/produtos': typeof ProdutosRouteWithChildren
  '/produtos/importacao': typeof ProdutosImportacaoRoute
  '/produtos/': typeof ProdutosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/historico'
    | '/orcamentos'
    | '/pagamentos'
    | '/pedidos'
    | '/producao'
    | '/produtos'
    | '/produtos/importacao'
    | '/produtos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/historico'
    | '/orcamentos'
    | '/pagamentos'
    | '/pedidos'
    | '/producao'
    | '/produtos/importacao'
    | '/produtos'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/historico'
    | '/orcamentos'
    | '/pagamentos'
    | '/pedidos'
    | '/producao'
    | '/produtos'
    | '/produtos/importacao'
    | '/produtos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRoute
  HistoricoRoute: typeof HistoricoRoute
  OrcamentosRoute: typeof OrcamentosRoute
  PagamentosRoute: typeof PagamentosRoute
  PedidosRoute: typeof PedidosRoute
  ProducaoRoute: typeof ProducaoRoute
  ProdutosRoute: typeof ProdutosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producao': {
      id: '/producao'
      path: '/producao'
      fullPath: '/producao'
      preLoaderRoute: typeof ProducaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamentos': {
      id: '/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof PagamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos': {
      id: '/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof OrcamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/': {
      id: '/produtos/'
      path: '/'
      fullPath: '/produtos/'
      preLoaderRoute: typeof ProdutosIndexRouteImport
      parentRoute: typeof ProdutosRoute
    }
    '/produtos/importacao': {
      id: '/produtos/importacao'
      path: '/importacao'
      fullPath: '/produtos/importacao'
      preLoaderRoute: typeof ProdutosImportacaoRouteImport
      parentRoute: typeof ProdutosRoute
    }
  }
}

interface ProdutosRouteChildren {
  ProdutosImportacaoRoute: typeof ProdutosImportacaoRoute
  ProdutosIndexRoute: typeof ProdutosIndexRoute
}

const ProdutosRouteChildren: ProdutosRouteChildren = {
  ProdutosImportacaoRoute: ProdutosImportacaoRoute,
  ProdutosIndexRoute: ProdutosIndexRoute,
}

const ProdutosRouteWithChildren = ProdutosRoute._addFileChildren(
  ProdutosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRoute,
  HistoricoRoute: HistoricoRoute,
  OrcamentosRoute: OrcamentosRoute,
  PagamentosRoute: PagamentosRoute,
  PedidosRoute: PedidosRoute,
  ProducaoRoute: ProducaoRoute,
  ProdutosRoute: ProdutosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
